### PR TITLE
Update InkBot to use version 19 of the Ink script

### PR DESCRIPTION
**Pull request by JanSimek**
Hello, thank you for creating such an interesting project. 

The blade-ink dependency is outdated and is incompatible with the JSON story exported from the latest release of the Inky editor.

### CODE REVIEW

**Comment by JanSimek** [comment]
There is a problem with this pull request. Intents are correctly matched, but one line responses such as to WhereTaxi and CancelTaxi return empty responses from `BotResponse::getResponse()`. Failed tests:

- testTaxiStatus
- testCancelTaxi
- testSessionEndClearsReprompts

**Comment by JanSimek** [comment]
Alright, I figured out what is wrong. If you look at the `InkBot::processStory()` method you will find this check:

```java
// skip first line as ink replays choice first
if (first && skipfirst)
{
    first = false;
    continue;
}
```

That's why there is no response text.

**Comment by rabidgremlin** [comment]
Interesting. They must have changed the behavior of ink between versions. Will need to investigate when this took place and see what other side effects may exist.

**Comment by JanSimek** [comment]
So the ink parser still returns the first line, however, the inkscript did not have a new line after each intent, so it got returned together with the response. Here is a fix:

```diff
diff --git a/mutters-ink-bot/src/test/ink/taxi/intents.ink b/mutters-ink-bot/src/test/ink/taxi/intents.ink
index 00489a4..d4e8f02 100644
--- a/mutters-ink-bot/src/test/ink/taxi/intents.ink
+++ b/mutters-ink-bot/src/test/ink/taxi/intents.ink
@@ -1,6 +1,7 @@
 == start ==
-+ OrderTaxi -> order_taxi
-+ CancelTaxi -> cancel_taxi
-+ WhereTaxi -> where_taxi
-
-
++ OrderTaxi
+    -> order_taxi
++ CancelTaxi
+    -> cancel_taxi
++ WhereTaxi
+    -> where_taxi
```

All the taxibot tests are now passed, but Orderbot tests fail and I cannot figure out why.

**Comment by rabidgremlin** [comment]
@JanSimek Finally got Mutters updated to use the latest version of Ink (v0.8.3). Turns out there was a bug in the later versions of blade-ink that needed to be fix: https://github.com/bladecoder/blade-ink/issues/15

Latest release info here: https://github.com/rabidgremlin/Mutters/releases/tag/v5.0.0

**Comment by JanSimek** [comment]
Great! Thank you

**Pull request closed without merging**
