### PR TITLE
create common implementations of DefaultValueSlot

### PR DESCRIPTION
**Pull request by wilmol**
@rabidgremlin not sure this needs to be in mutters

but have noticed all DefaultValueSlots either use "" or -1

also as discussed there is a conflict with absent LocalDate matches (StoryUtils accepts empty string but SessionUtils logs a WARN), so maybe good to standardise on LocalDate.MIN ??

### CODE REVIEW

**Comment by rabidgremlin** [comment]
mmm, Defaulting to LocalDate.MIN or -1 means you can't test for "null"....

As you say this doesn't really belong in Mutters  but it could be useful. I'm happy to add it but it needs some tests :)

**Comment by wilmol** [comment]
@rabidgremlin  can't use null because `SlotMatch` rejects null

**Comment by rabidgremlin** [comment]
Understood but an "" can be used to represent a null or "not set". Which you lose if you default to LocalDate.MIN not a problem since someone can override this behavior if they want.

BTW if you are defaulting to LocalDate.MIN what are you comparing to in the Ink scripts as you can't use "" anymore ?

**Comment by wilmol** [comment]
The problem with "" is it is a different type now so cant be used (unless you declare the Slot as `Slot<Object>`).

In ink I use `CONST DEFAULT_DATE = "-999999999-01-01"` which isn't that bad; more annoying to deal with when the values are read into Java (replaced the null checks with LocalDate.MIN checks...).

**Comment by rabidgremlin** [comment]
Cool. That make sense.

**Pull request merged**
